# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9a267b0a4d307a8336890e7fafc0dfe491a9b0d0642d1aa1a53f0eefe9050de7e1ce46ab902cc92999b36eaf9a0799a12569a46dcfd2c2501281b0373e8d717

test:
  secret_key_base: 3f1410a769da7bb80305d5b17705504521bea47926c2f70895c40c5d1d35ce3dedc48188a555300a701d0b610cafc4a91038347edd247b6e82bbf2cbb5196370

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
